# Generated by Django 6.0.3 on 2026-03-16 05:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
        ('settlements', '0002_receipt_settlements_receipt_total_amount_nonnegative_and_more'),
        ('trips', '0002_trip_trips_trip_capacity_range_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TRIP_LEADER_SUCCESS', 'TRIP_LEADER_SUCCESS'), ('TRIP_PARTICIPATION_COMPLETED', 'TRIP_PARTICIPATION_COMPLETED'), ('FAST_SETTLEMENT', 'FAST_SETTLEMENT'), ('STREAK_BONUS', 'STREAK_BONUS'), ('NORMAL_CANCEL', 'NORMAL_CANCEL'), ('URGENT_CANCEL', 'URGENT_CANCEL'), ('NO_SHOW', 'NO_SHOW'), ('MANUAL_ADJUST', 'MANUAL_ADJUST')], max_length=40)),
                ('direction', models.CharField(choices=[('GAIN', 'GAIN'), ('PENALTY', 'PENALTY'), ('ADJUST', 'ADJUST')], max_length=10)),
                ('raw_base_score', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('-20.0')), django.core.validators.MaxValueValidator(Decimal('20.0'))])),
                ('applied_delta', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('-20.0')), django.core.validators.MaxValueValidator(Decimal('20.0'))])),
                ('score_before', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('99.9'))])),
                ('score_after', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('99.9'))])),
                ('formula_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('reason_detail', models.TextField(blank=True, null=True)),
                ('streak_count_after', models.PositiveIntegerField(blank=True, null=True)),
                ('is_warning_triggered', models.BooleanField(default=False)),
                ('created_by_system', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='penalty',
            constraint=models.CheckConstraint(condition=models.Q(('points__gt', 0)), name='moderation_penalty_points_positive'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='moderation_review_rating_range'),
        ),
        migrations.AddField(
            model_name='trustscorelog',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_trust_score_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trustscorelog',
            name='related_penalty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_score_logs', to='moderation.penalty'),
        ),
        migrations.AddField(
            model_name='trustscorelog',
            name='related_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_score_logs', to='moderation.review'),
        ),
        migrations.AddField(
            model_name='trustscorelog',
            name='related_settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_score_logs', to='settlements.settlement'),
        ),
        migrations.AddField(
            model_name='trustscorelog',
            name='related_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_score_logs', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='trustscorelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_score_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='trustscorelog',
            constraint=models.CheckConstraint(condition=models.Q(('raw_base_score__gte', -20.0), ('raw_base_score__lte', 20.0)), name='moderation_trustscorelog_raw_base_score_range'),
        ),
        migrations.AddConstraint(
            model_name='trustscorelog',
            constraint=models.CheckConstraint(condition=models.Q(('applied_delta__gte', -20.0), ('applied_delta__lte', 20.0)), name='moderation_trustscorelog_applied_delta_range'),
        ),
        migrations.AddConstraint(
            model_name='trustscorelog',
            constraint=models.CheckConstraint(condition=models.Q(('score_before__gte', 0.0), ('score_before__lte', 99.9)), name='moderation_trustscorelog_score_before_range'),
        ),
        migrations.AddConstraint(
            model_name='trustscorelog',
            constraint=models.CheckConstraint(condition=models.Q(('score_after__gte', 0.0), ('score_after__lte', 99.9)), name='moderation_trustscorelog_score_after_range'),
        ),
        migrations.AddConstraint(
            model_name='trustscorelog',
            constraint=models.CheckConstraint(condition=models.Q(('streak_count_after__isnull', True), ('streak_count_after__gte', 0), _connector='OR'), name='moderation_trustscorelog_streak_count_nonnegative_or_null'),
        ),
    ]
