# Generated by Django 6.0.3 on 2026-03-16 05:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 2), ('capacity__lte', 4)), name='trips_trip_capacity_range'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_fare__isnull', True), ('estimated_fare__gte', 0), _connector='OR'), name='trips_trip_estimated_fare_nonnegative_or_null'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('depart_lat__gte', -90), ('depart_lat__lte', 90)), name='trips_trip_depart_lat_range'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('depart_lng__gte', -180), ('depart_lng__lte', 180)), name='trips_trip_depart_lng_range'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('arrive_lat__gte', -90), ('arrive_lat__lte', 90)), name='trips_trip_arrive_lat_range'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('arrive_lng__gte', -180), ('arrive_lng__lte', 180)), name='trips_trip_arrive_lng_range'),
        ),
    ]
