# Generated by Django 6.0.3 on 2026-03-16 05:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settlements', '0001_initial'),
        ('trips', '0002_trip_trips_trip_capacity_range_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='settlements_receipt_total_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('share_amount__gte', 0)), name='settlements_settlement_share_amount_nonnegative'),
        ),
    ]
